package cloud.contoterzi.helpdesk.core.model;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Represents a response generated by a large language model (LLM).
 * This class encapsulates the response text and the time it took to generate.
 * It can serve as a standard representation of LLM responses in the system.
 */
public class LlmResponse extends LlmBaseFields {
    /**
     * The time in milliseconds when the LLM response was generated.
     */
    private long timeMs;

    /**
     * Default empty constructor.
     */
    public LlmResponse() {
        this("", 0);
    }

    public LlmResponse(String answer) {
        this(answer, 0);
    }

    /**
     * Creates a new instance of LlmResponse.
     * @param answer The text of the response. The response from the LLM is
     * usually a string, if not, it can be converted to a String.
     * @param timeMs The time in milliseconds when the response was generated.
     */
    public LlmResponse(String answer, long timeMs) {
        super(answer);
        this.timeMs = timeMs;
    }


    /**
     * Gets the textual response from the LLM.
     * @return The textual response.
     */
    public String getAnswer() {
        return text;
    }

    /**
     * Sets the textual response from the LLM.
     * @param answer The textual response.
     */
    public void setAnswer(String answer) {
        this.text = answer;
    }

    /**
     * Gets the time in milliseconds when the LLM response was generated.
     * @return The time in milliseconds.
     */
    public long getTimeMs() {
        return timeMs;
    }

    /**
     * Sets the time in milliseconds when the LLM response was generated.
     * @param timeMs The time in milliseconds.
     */
    public void setTimeMs(long timeMs) {
        this.timeMs = timeMs;
    }
}