llm:
  type: claude
  region: us-east-1
  modelId: anthropic.claude-3-sonnet-20240229-v1:0
  llmVersion: bedrock-2023-05-31
  temperature: 0.4
  maxTokens: 1024
  prompts:
    preamble: >- 
              You are a test help desk assistant for an agricultural subcontractor management software. 
              Answer clearly and helpfully only if the question is relevant to the software. 
              If it is not, state that you cannot answer. 
              If the user needs human intervention, include EXACTLY the phrase 'contact support' once in the answer. 
              If no human is required, DO NOT include that phrase.
    template: "%s%n%nTest Examples:%n%s%n%nUser question: %s%nAnswer:"
    contactSupportPhrase: "contact support"

storage:
  type: s3
  region: eu-north-1
  bucket: test-bucket
  prefix: ""
  filename: test-knowledge.json

similarity:
  type: cosine
  fewShot: 10000
  threshold: 0.8